/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserTrackingRouteImport } from './routes/user.tracking'
import { Route as UserSettingsRouteImport } from './routes/user.settings'
import { Route as UserScheduleRouteImport } from './routes/user.schedule'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as UserBookingsRouteImport } from './routes/user.bookings'
import { Route as UserBookPickupRouteImport } from './routes/user.book-pickup'
import { Route as CollectorProfileRouteImport } from './routes/collector.profile'
import { Route as CollectorJobsRouteImport } from './routes/collector.jobs'
import { Route as CollectorHistoryRouteImport } from './routes/collector.history'
import { Route as CollectorEarningsRouteImport } from './routes/collector.earnings'
import { Route as CollectorDashboardRouteImport } from './routes/collector.dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCollectorsRouteImport } from './routes/admin.collectors'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CollectorJobIdRouteImport } from './routes/collector.job.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTrackingRoute = UserTrackingRouteImport.update({
  id: '/user/tracking',
  path: '/user/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user/settings',
  path: '/user/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserScheduleRoute = UserScheduleRouteImport.update({
  id: '/user/schedule',
  path: '/user/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBookingsRoute = UserBookingsRouteImport.update({
  id: '/user/bookings',
  path: '/user/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const UserBookPickupRoute = UserBookPickupRouteImport.update({
  id: '/user/book-pickup',
  path: '/user/book-pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorProfileRoute = CollectorProfileRouteImport.update({
  id: '/collector/profile',
  path: '/collector/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorJobsRoute = CollectorJobsRouteImport.update({
  id: '/collector/jobs',
  path: '/collector/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorHistoryRoute = CollectorHistoryRouteImport.update({
  id: '/collector/history',
  path: '/collector/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorEarningsRoute = CollectorEarningsRouteImport.update({
  id: '/collector/earnings',
  path: '/collector/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorDashboardRoute = CollectorDashboardRouteImport.update({
  id: '/collector/dashboard',
  path: '/collector/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectorsRoute = AdminCollectorsRouteImport.update({
  id: '/admin/collectors',
  path: '/admin/collectors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/admin/bookings',
  path: '/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorJobIdRoute = CollectorJobIdRouteImport.update({
  id: '/collector/job/$id',
  path: '/collector/job/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/collector/dashboard': typeof CollectorDashboardRoute
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/history': typeof CollectorHistoryRoute
  '/collector/jobs': typeof CollectorJobsRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/user/book-pickup': typeof UserBookPickupRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/profile': typeof UserProfileRoute
  '/user/schedule': typeof UserScheduleRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/tracking': typeof UserTrackingRoute
  '/collector/job/$id': typeof CollectorJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/collector/dashboard': typeof CollectorDashboardRoute
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/history': typeof CollectorHistoryRoute
  '/collector/jobs': typeof CollectorJobsRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/user/book-pickup': typeof UserBookPickupRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/profile': typeof UserProfileRoute
  '/user/schedule': typeof UserScheduleRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/tracking': typeof UserTrackingRoute
  '/collector/job/$id': typeof CollectorJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/collector/dashboard': typeof CollectorDashboardRoute
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/history': typeof CollectorHistoryRoute
  '/collector/jobs': typeof CollectorJobsRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/user/book-pickup': typeof UserBookPickupRoute
  '/user/bookings': typeof UserBookingsRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/profile': typeof UserProfileRoute
  '/user/schedule': typeof UserScheduleRoute
  '/user/settings': typeof UserSettingsRoute
  '/user/tracking': typeof UserTrackingRoute
  '/collector/job/$id': typeof CollectorJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/collectors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/collector/dashboard'
    | '/collector/earnings'
    | '/collector/history'
    | '/collector/jobs'
    | '/collector/profile'
    | '/user/book-pickup'
    | '/user/bookings'
    | '/user/dashboard'
    | '/user/profile'
    | '/user/schedule'
    | '/user/settings'
    | '/user/tracking'
    | '/collector/job/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/collectors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/collector/dashboard'
    | '/collector/earnings'
    | '/collector/history'
    | '/collector/jobs'
    | '/collector/profile'
    | '/user/book-pickup'
    | '/user/bookings'
    | '/user/dashboard'
    | '/user/profile'
    | '/user/schedule'
    | '/user/settings'
    | '/user/tracking'
    | '/collector/job/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/services'
    | '/sitemap.xml'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/collectors'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/collector/dashboard'
    | '/collector/earnings'
    | '/collector/history'
    | '/collector/jobs'
    | '/collector/profile'
    | '/user/book-pickup'
    | '/user/bookings'
    | '/user/dashboard'
    | '/user/profile'
    | '/user/schedule'
    | '/user/settings'
    | '/user/tracking'
    | '/collector/job/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminCollectorsRoute: typeof AdminCollectorsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CollectorDashboardRoute: typeof CollectorDashboardRoute
  CollectorEarningsRoute: typeof CollectorEarningsRoute
  CollectorHistoryRoute: typeof CollectorHistoryRoute
  CollectorJobsRoute: typeof CollectorJobsRoute
  CollectorProfileRoute: typeof CollectorProfileRoute
  UserBookPickupRoute: typeof UserBookPickupRoute
  UserBookingsRoute: typeof UserBookingsRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserProfileRoute: typeof UserProfileRoute
  UserScheduleRoute: typeof UserScheduleRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserTrackingRoute: typeof UserTrackingRoute
  CollectorJobIdRoute: typeof CollectorJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/tracking': {
      id: '/user/tracking'
      path: '/user/tracking'
      fullPath: '/user/tracking'
      preLoaderRoute: typeof UserTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/settings': {
      id: '/user/settings'
      path: '/user/settings'
      fullPath: '/user/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/schedule': {
      id: '/user/schedule'
      path: '/user/schedule'
      fullPath: '/user/schedule'
      preLoaderRoute: typeof UserScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/bookings': {
      id: '/user/bookings'
      path: '/user/bookings'
      fullPath: '/user/bookings'
      preLoaderRoute: typeof UserBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/book-pickup': {
      id: '/user/book-pickup'
      path: '/user/book-pickup'
      fullPath: '/user/book-pickup'
      preLoaderRoute: typeof UserBookPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/profile': {
      id: '/collector/profile'
      path: '/collector/profile'
      fullPath: '/collector/profile'
      preLoaderRoute: typeof CollectorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/jobs': {
      id: '/collector/jobs'
      path: '/collector/jobs'
      fullPath: '/collector/jobs'
      preLoaderRoute: typeof CollectorJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/history': {
      id: '/collector/history'
      path: '/collector/history'
      fullPath: '/collector/history'
      preLoaderRoute: typeof CollectorHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/earnings': {
      id: '/collector/earnings'
      path: '/collector/earnings'
      fullPath: '/collector/earnings'
      preLoaderRoute: typeof CollectorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/dashboard': {
      id: '/collector/dashboard'
      path: '/collector/dashboard'
      fullPath: '/collector/dashboard'
      preLoaderRoute: typeof CollectorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collectors': {
      id: '/admin/collectors'
      path: '/admin/collectors'
      fullPath: '/admin/collectors'
      preLoaderRoute: typeof AdminCollectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/admin/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector/job/$id': {
      id: '/collector/job/$id'
      path: '/collector/job/$id'
      fullPath: '/collector/job/$id'
      preLoaderRoute: typeof CollectorJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminCollectorsRoute: AdminCollectorsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CollectorDashboardRoute: CollectorDashboardRoute,
  CollectorEarningsRoute: CollectorEarningsRoute,
  CollectorHistoryRoute: CollectorHistoryRoute,
  CollectorJobsRoute: CollectorJobsRoute,
  CollectorProfileRoute: CollectorProfileRoute,
  UserBookPickupRoute: UserBookPickupRoute,
  UserBookingsRoute: UserBookingsRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserProfileRoute: UserProfileRoute,
  UserScheduleRoute: UserScheduleRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserTrackingRoute: UserTrackingRoute,
  CollectorJobIdRoute: CollectorJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
